a# Site settings
title: ManyPrimates
subtitle: 
email: manyprimates@gmail.com
description: Establishing a Culture of Collaboration in Primate Cognition Research
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://manyprimates.github.io" # the base hostname & protocol for your site
author: ManyPrimates
lang: en_US

# Social
twitter:
  username: ManyPrimates
  card: summary

# Social settings
github_url: https://github.com/ManyPrimates
slack_url: https://join.slack.com/t/manyprimates/shared_invite/zt-5jzcn4xz-cdzlToDOl6m4P9ewrp22vA
twitter_url: https://twitter.com/ManyPrimates
osf_url: https://osf.io/tr6q3/
instagram_url: https://twitter.com/ManyPrimates
bluesky_url: https://bsky.app/profile/did:plc:nuhmja746x4qtof2npwr2rzy

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
